### ISSUE TITLE
Can't Log In

### ISSUE THREAD

**Issue by cinderblockgames** [gramps-project/gramps-web#341] opened 2023-12-31 12:58 UTC
If I log out, I can't log back in -- the login page gives me a 422 Unprocessable Content on /api/token.

**Comment by DavidMStraub** [comment] 2023-12-31 14:09
I suspect it's an issue with a password manager. Please try typing both user name and password manually (even if it was already pre-filled). Related: #310

**Comment by DavidMStraub** [comment] 2024-01-21 20:24
Closing as assumed duplicate of #310.

**Closed by DavidMStraub** 2024-01-21 20:24 UTC
Labels: question
