### ISSUE TITLE
[BUG] Unable to run docker in a multi-tree setup

### ISSUE THREAD

**Issue by Corepex** [gramps-project/gramps-web#456] opened 2024-06-23 22:37 UTC
## IF

... I take the following [docker-compose](https://github.com/gramps-project/gramps-web-docs/blob/main/examples/docker-compose-base/docker-compose.yml) file, as suggested in the docs, as a template and change the `GRAMPSWEB_TREE` option to `*` as suggested [here](https://github.com/gramps-project/gramps-web-docs/blob/main/docs/multi-tree.md?plain=1#L8-L14)

I get the following error in the logs:  `tree is required when multi-tree support is enabled.`

#### Note:

I also tried to switch an existing setup to a multi-tree setup but i couldn't figure out how to create a tree. 
EVEN with the official API docs from https://gramps-project.github.io/gramps-web-api/#/. 

I provided the documented options via `query` and/or `body` (as json). But the only thing i get back are the details from the existing tree without the creation of the new one ... how can i proceed here?

**Comment by DavidMStraub** [comment] 2024-06-24 06:05
Duplicate of https://github.com/gramps-project/gramps-web-api/issues/510.

**Closed by DavidMStraub** 2024-06-24 06:05 UTC

**Comment by Corepex** [comment] 2024-06-24 13:29
> I also tried to switch an existing setup to a multi-tree setup but i couldn't figure out how to create a tree. EVEN with the official API docs from https://gramps-project.github.io/gramps-web-api/#/.
> 
> I provided the documented options via `query` and/or `body` (as json). But the only thing i get back are the details from the existing tree without the creation of the new one ... how can i proceed here?



@DavidMStraub do you have any advice for the second part?

**Comment by DavidMStraub** [comment] 2024-06-24 13:32
You need to `POST` to `/api/trees/`, you will get back the details of the new tree.

**Comment by Corepex** [comment] 2024-06-24 14:17
![image](https://github.com/gramps-project/gramps-web/assets/16717695/cc2251fa-76df-4391-af19-5b69963e0eea)


yeah thats what the docs say. But it doesnt work for me ... also couldn't find something in the logs ...

**Comment by DavidMStraub** [comment] 2024-06-24 14:25
So, it looks like `15e7...` is a new directory that was created in your Gramps home. Where is the problem?

**Comment by DavidMStraub** [comment] 2024-06-24 14:25
Maybe you are confused by the fact that you have multiple trees that are all called "Gramps Web"? `gramps -l` could help.

**Comment by Corepex** [comment] 2024-06-24 14:30
> Maybe you are confused by the fact that you have multiple trees that are all called "Gramps Web"? `gramps -l` could help.

I checked that with `python3 -m gramps_webapi tree list`. Nothing was created or changed. The `15e7` tree is the default one I created when setting up gramps-web ...

Besides that, it's a bit weird that if I create a tree with the name `testtree`, it returns me another tree with a totally different name. Or?

**Comment by DavidMStraub** [comment] 2024-06-24 14:31
Yes 🫤

**Comment by DavidMStraub** [comment] 2024-06-24 14:32
But please add to an existing ticket in the web API repo or create a new one if needed, here it will get lost.
